### ISSUE TITLE
Se due S si incontrano uno diventa infetto?

### ISSUE THREAD

**Issue by mariopaolucci** [LABSS/abm_sir#2]
https://github.com/LABSS/abm_sir/blob/7d21343457a412e3049d62b507f77ad42659c1b7/abm_sir.nlogo#L30

**Comment by cecconifederico** [comment]
No, due S non possono diventare un I.  infatti se fai girare la simulazione in modalità test con M_perc =0 (nessun I iniziale) il numero di infettati rimane zero, 

https://docs.google.com/document/d/1wjWs3632AUAOquWzUy1g_ikAvAKI4UQ2tBvxaQZTMXQ/edit?usp=sharing

la difficoltà nell'implementare il contagio deriva da una richiesta di Vilone, 

_At each elementary step a random agent is extracted, let's call it k: **if k is an S**, one of its neighbors is extracted (i.e. any other agent if we are in the mean field, one of its 4 or 8 first neighbors in the other two), and if this neighbor is an I (infected), with probability BETA (see point 7) k becomes I too._

prima parte, poi

_For the moment BETA is a fixed parameter of the model, but when we refine the model it will vary, over time and from agent to agent (how we will see it). If agent **k is an I**, two things are done: a) a neighbor is extracted (similarly to point 5), **if this neighbor is an S, with probability BETA also this neighbor becomes I, b) then with probability GAMMA agent k becomes R.**_

il che  significa, per essere aderenti, dover implementare ESPLICITAMENTE entrambe le alternative. Io ho risolto creando la procedura **update_infected** (che devo ancora documentare) che riceve in ingresso CHI DEVO CERCARE. Quindi se viene chiamata da un I allora cerca un S, e viceversa
